import unittest
from app import rotateLeft, rotateRight, encryptString

class CaesarCipherTest(unittest.TestCase):
   def rotateLeftTest(self):
      newList = rotateLeft([1,2,3,4,5,6,7,8], 3)
      self.assertEqual(newList, [4, 5, 6, 7, 1, 2, 3])
   
   def rotateRightTest(self):
      newList = rotateRight([1,2,3,4,5,6,7,8], 4)
      self.assertEqual(newList, [5, 6, 7, 8, 1, 2, 3, 4])
   
   def encryptionTest(self):
      initialText = "Chandler Bing"
      cipherText = encryptString(initialText, 5)
      self.assertEqual(cipherText, "Hmfsiqjw Gnsl")

      longerText = "Lorem ipsum dolor sit amet, nulla ut sem vestibulum nunc ut, pellentesque aliquam, libero vestibulum aliquam, porta massa eu eget auctor, egestas felis faucibus accumsan ac. Blandit in, ut non erat nascetur non. Ante auctor ante scelerisque purus pellentesque in, tellus facilisis malesuada, sed dolor laoreet, aenean vel. At vivamus diam porttitor. Bibendum sociosqu sed tempus etiam diam, ultrices in aenean pede molestie, duis fusce consequat placerat lectus porttitor. Vestibulum scelerisque viverra justo ultricies at consequat, lorem mollis congue, ligula elit, litora magna risus ut ultricies. In orci. Orci est tellus, ac proin non magna orci nostra enim. Vivamus non nibh amet, laoreet fusce. Non enim ultricies ac, in aliquam hic. Elit non duis, gravida dapibus orci donec aliquam lectus non. Enim eros pharetra cubilia, vestibulum massa conubia, donec blandit dolor duis eget montes, faucibus sociosqu morbi, donec nunc wisi. Arcu justo, sed in non tristique etiam, ut suscipit, in sed, in in in vestibulum phasellus accumsan quisque. Ante cursus cras rutrum, mauris dolor aliquam sed. Quis sit ornare augue vitae, tortor sed est dui, leo neque quis ac suscipit id at, nec tortor luctus elit suspendisse lorem curabitur, nulla velit sed eleifend. Vitae morbi porttitor eget, dolor quis nullam pharetra gravida enim sit, pretium hac dolor imperdiet ullamcorper lacinia mauris. Orci amet ut sit fusce sodales, nisl nibh orci purus non a. A gravida sollicitudin ipsum eros lorem fusce, imperdiet suspendisse, congue tempor iaculis, varius cras metus arcu vulputate integer. Auctor nonummy mauris porttitor maecenas vestibulum vestibulum, ridiculus turpis dapibus consequat, pharetra adipiscing aliquam nullam ut lorem felis, maecenas eu et. Varius in commodo integer justo. Fringilla phasellus vestibulum mauris sapien enim in, donec imperdiet sit consectetuer pretium viverra per, nec sed ipsum dui diam, vestibulum pellentesque eget porttitor. Elit sit in non est nunc, cursus voluptas pellentesque bibendum vivamus, interdum urna tortor ut pellentesque est, tincidunt vestibulum ut tristique orci nisl. Diam pulvinar a adipiscing felis, elit a quis suspendisse mauris, sodales bibendum donec est, a ut vitae ultrices. Nec ipsum sit pharetra dis. Non ullamcorper dolor, eu pellentesque arcu earum nemo nunc sit. Libero mi id quam dui lorem dui, eget feugiat, urna morbi feugiat, felis metus feugiat. Accumsan magna lorem, nunc nam consequat metus velit a, per suscipit. Sodales venenatis quis proin vel, mauris justo nunc, aliquam magna libero sodales nullam lectus, nec erat curae mauris suspendisse, suspendisse dolor vestibulum. Nibh ligula nec integer. Elit aliquet donec lacus."
      longerCipherText = encryptString(longerText, 5)
      self.assertEqual(longerCipherText, "Qtwjr nuxzr itqtw xny frjy, szqqf zy xjr ajxyngzqzr szsh zy, ujqqjsyjxvzj fqnvzfr, qngjwt ajxyngzqzr fqnvzfr, utwyf rfxxf jz jljy fzhytw, jljxyfx kjqnx kfzhngzx fhhzrxfs fh. Gqfsiny ns, zy sts jwfy sfxhjyzw sts. Fsyj fzhytw fsyj xhjqjwnxvzj uzwzx ujqqjsyjxvzj ns, yjqqzx kfhnqnxnx rfqjxzfif, xji itqtw qftwjjy, fjsjfs ajq. Fy anafrzx infr utwyynytw. Gngjsizr xthntxvz xji yjruzx jynfr infr, zqywnhjx ns fjsjfs ujij rtqjxynj, iznx kzxhj htsxjvzfy uqfhjwfy qjhyzx utwyynytw. Ajxyngzqzr xhjqjwnxvzj anajwwf ozxyt zqywnhnjx fy htsxjvzfy, qtwjr rtqqnx htslzj, qnlzqf jqny, qnytwf rflsf wnxzx zy zqywnhnjx. Ns twhn. Twhn jxy yjqqzx, fh uwtns sts rflsf twhn stxywf jsnr. Anafrzx sts sngm frjy, qftwjjy kzxhj. Sts jsnr zqywnhnjx fh, ns fqnvzfr mnh. Jqny sts iznx, lwfanif ifungzx twhn itsjh fqnvzfr qjhyzx sts. Jsnr jwtx umfwjywf hzgnqnf, ajxyngzqzr rfxxf htszgnf, itsjh gqfsiny itqtw iznx jljy rtsyjx, kfzhngzx xthntxvz rtwgn, itsjh szsh bnxn. Fwhz ozxyt, xji ns sts ywnxynvzj jynfr, zy xzxhnuny, ns xji, ns ns ns ajxyngzqzr umfxjqqzx fhhzrxfs vznxvzj. Fsyj hzwxzx hwfx wzywzr, rfzwnx itqtw fqnvzfr xji. Vznx xny twsfwj fzlzj anyfj, ytwytw xji jxy izn, qjt sjvzj vznx fh xzxhnuny ni fy, sjh ytwytw qzhyzx jqny xzxujsinxxj qtwjr hzwfgnyzw, szqqf ajqny xji jqjnkjsi. Anyfj rtwgn utwyynytw jljy, itqtw vznx szqqfr umfwjywf lwfanif jsnr xny, uwjynzr mfh itqtw nrujwinjy zqqfrhtwujw qfhnsnf rfzwnx. Twhn frjy zy xny kzxhj xtifqjx, snxq sngm twhn uzwzx sts f. F lwfanif xtqqnhnyzins nuxzr jwtx qtwjr kzxhj, nrujwinjy xzxujsinxxj, htslzj yjrutw nfhzqnx, afwnzx hwfx rjyzx fwhz azquzyfyj nsyjljw. Fzhytw stszrrd rfzwnx utwyynytw rfjhjsfx ajxyngzqzr ajxyngzqzr, wninhzqzx yzwunx ifungzx htsxjvzfy, umfwjywf finunxhnsl fqnvzfr szqqfr zy qtwjr kjqnx, rfjhjsfx jz jy. Afwnzx ns htrrtit nsyjljw ozxyt. Kwnslnqqf umfxjqqzx ajxyngzqzr rfzwnx xfunjs jsnr ns, itsjh nrujwinjy xny htsxjhyjyzjw uwjynzr anajwwf ujw, sjh xji nuxzr izn infr, ajxyngzqzr ujqqjsyjxvzj jljy utwyynytw. Jqny xny ns sts jxy szsh, hzwxzx atqzuyfx ujqqjsyjxvzj gngjsizr anafrzx, nsyjwizr zwsf ytwytw zy ujqqjsyjxvzj jxy, ynshnizsy ajxyngzqzr zy ywnxynvzj twhn snxq. Infr uzqansfw f finunxhnsl kjqnx, jqny f vznx xzxujsinxxj rfzwnx, xtifqjx gngjsizr itsjh jxy, f zy anyfj zqywnhjx. Sjh nuxzr xny umfwjywf inx. Sts zqqfrhtwujw itqtw, jz ujqqjsyjxvzj fwhz jfwzr sjrt szsh xny. Qngjwt rn ni vzfr izn qtwjr izn, jljy kjzlnfy, zwsf rtwgn kjzlnfy, kjqnx rjyzx kjzlnfy. Fhhzrxfs rflsf qtwjr, szsh sfr htsxjvzfy rjyzx ajqny f, ujw xzxhnuny. Xtifqjx ajsjsfynx vznx uwtns ajq, rfzwnx ozxyt szsh, fqnvzfr rflsf qngjwt xtifqjx szqqfr qjhyzx, sjh jwfy hzwfj rfzwnx xzxujsinxxj, xzxujsinxxj itqtw ajxyngzqzr. Sngm qnlzqf sjh nsyjljw. Jqny fqnvzjy itsjh qfhzx.")

if __name__ == '__main__':
   unittest.main()